In [19]:
import numpy as np

In [20]:
x = np.arange(9)
y=x**2
x,y

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 0,  1,  4,  9, 16, 25, 36, 49, 64]))

In [21]:
# saving np array as zip file
np.savez("this.npz",k = x,y_axis = y)

In [22]:
del x,y

In [23]:
%whos

Variable   Type       Data/Info
-------------------------------
load_xy    NpzFile    NpzFile 'this.npz' with keys: k, y_axis
np         module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>


In [24]:
load_xy = np.load("this.npz")
print(load_xy.files)

['k', 'y_axis']


In [27]:
x = load_xy["k"]
x =x.reshape(3,3)

In [29]:
np.savetxt("this.csv",X=x,delimiter=",")

In [30]:
del x

In [32]:
x = np.loadtxt("this.csv",delimiter=",")
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])